# Programming and Data Analysis

> Assignment 4

Kuo, Yao-Jen <yaojenkuo@ntu.edu.tw> from [DATAINPOINT](https://www.datainpoint.com)

In [ ]:
import unittest
import numpy as np

## Instructions

- We've imported necessary modules at the top of each assignment.
- We've defined the names of functions/inputs/parameters for you.
- Save a copy in your own Google Drive before getting started.
    - File -> Save a copy in Drive.
- Write down your solution between the comments `### BEGIN SOLUTION` and `### END SOLUTION`.
- It is NECESSARY to `return` the answer, tests will fail by just printing out the answer.
- DON'Ts
    - DON'T use `input()` function in your assignments.
    - DON'T use Safari browser to export Colab as Python script.
    - DON'T nest your solution in another `def` function code block. 
- Running tests to see if your solutions are right:
    - File -> Save.
    - Runtime -> Restart and run all.
- When you are ready to submit, click File -> Download -> Download `.py`.

![](https://i.imgur.com/Y1BcDdx.png)

- Open a new Colab in a private window, upload the script and run tests again before submission to make sure the script is executable in a fresh new Colab.

![](https://i.imgur.com/ojlvbds.png)

- Upload to the Assignment session on NTU COOL.

## 01. Define a class named `Hogwarts` which instantiates objects with 3 attributes `location`, `founders`, and `houses`.

In [ ]:
class Hogwarts:
    """
    >>> hogwarts = Hogwarts()
    >>> type(hogwarts)
    '__main__.Hogwarts'
    >>> hogwarts.location
    'Scotland'
    >>> hogwarts.founders
    ['Godric Gryffindor', 'Salazar Slytherin', 'Rowena Ravenclaw', 'Helga Hufflepuff']
    >>> hogwarts.houses
    ['Gryffindor', 'Slytherin', 'Ravenclaw', 'Hufflepuff']
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 02. Define a class named `Gryffindor` which instantiates objects with 2 attributes `traits` and `colors`, 1 method `cast_a_spell()`.

In [ ]:
class Gryffindor:
    """
    >>> harry_potter = Gryffindor("Harry Potter")
    >>> type(harry_potter)
    '__main__.Gryffindor'
    >>> harry_potter.name
    'Harry Potter'
    >>> harry_potter.traits
    ['courage', 'bravery', 'nerve', 'chivalry']
    >>> harry_potter.colors
    ['scarlet red', 'gold']
    >>> harry_potter.cast_a_spell()
    'Expelliarmus!'
    >>> hermione_granger = Gryffindor("Hermione Granger")
    >>> type(hermione_granger)
    '__main__.Gryffindor'
    >>> hermione_granger.name
    'Hermione Granger'
    >>> hermione_granger.traits
    ['courage', 'bravery', 'nerve', 'chivalry']
    >>> hermione_granger.colors
    ['scarlet red', 'gold']
    >>> hermione_granger.cast_a_spell()
    'Expelliarmus!'
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 03. Define a class named `Palindrome` which instantiates objects with 2 attributes `original_text` and `reversed_text`, and 1 method `is_palindrome()`.

In [ ]:
class Palindrome:
    """
    >>> palindrome = Palindrome('eye')
    >>> palindrome.original_text
    'eye'
    >>> palindrome.reversed_text
    'eye'
    >>> palindrome.is_palindrome()
    True
    >>> palindrome = Palindrome('dye')
    >>> palindrome.original_text
    'dye'
    >>> palindrome.reversed_text
    'eyd'
    >>> palindrome.is_palindrome()
    False
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 04. Define a class named `MinMaxFinder` instantiates objects with 1 attribute `integer_list` and 4 methods `find_min()`, `find_max()`, `find_idxmin()`, and `find_idxmax()`.

In [ ]:
class MinMaxFinder:
    """
    >>> min_max_finder = MinMaxFinder([2, 3, 5, 7, 11, 11, 7, 5, 3, 2])
    >>> min_max_finder.integer_list
    [2, 3, 5, 7, 11, 11, 7, 5, 3, 2]
    >>> min_max_finder.find_min()
    2
    >>> min_max_finder.find_max()
    11
    >>> min_max_finder.find_idxmin()
    [0, 9]
    >>> min_max_finder.find_idxmax()
    [4, 5]
    >>> min_max_finder = MinMaxFinder([10, 9, 8, 6, 4, 1, 1, 4, 6, 8, 9, 10])
    >>> min_max_finder.integer_list
    [10, 9, 8, 6, 4, 1, 1, 4, 6, 8, 9, 10]
    >>> min_max_finder.find_min()
    1
    >>> min_max_finder.find_max()
    10
    >>> min_max_finder.find_idxmin()
    [5, 6]
    >>> min_max_finder.find_idxmax()
    [0, 11]
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 05. Define a class named `CommonDivisors` which instantiates objects with 2 attributes `x_divisors` and `y_divisors`, and 1 method `get_common_divisors()`.

In [ ]:
class CommonDivisors:
    """
    >>> cd = CommonDivisors(3, 6)
    >>> cd.x_divisors
    {1, 3}
    >>> cd.y_divisors
    {1, 2, 3, 6}
    >>> cd.get_common_divisors()
    {1, 3}
    >>> cd = CommonDivisors(4, 8)
    >>> cd.x_divisors
    {1, 2, 4}
    >>> cd.y_divisors
    {1, 2, 4, 8}
    >>> cd.get_common_divisors()
    {1, 2, 4}
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 06. Define a class named `PrimeJudger` which instantiates objects with 2 methods `get_divisors()`, `is_prime()`.

In [ ]:
class PrimeJudger:
    """
    >>> pj = PrimeJudger(1)
    >>> pj.get_divisors()
    {1}
    >>> pj.is_prime()
    False
    >>> pj = PrimeJudger(2)
    >>> pj.get_divisors()
    {1, 2}
    >>> pj.is_prime()
    True
    >>> pj = PrimeJudger(4)
    >>> pj.get_divisors()
    {1, 2, 4}
    >>> pj.is_prime()
    False
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 07. Define a class named `ArrayGetAttrs` which instantiates objects with 4 methods `get_ndim()`, `get_shape()`, `get_size()`, and `get_dtype()`.

In [ ]:
class ArrayGetAttrs:
    """
    >>> arr = np.array([5, 5, 6, 6])
    >>> aga = ArrayGetAttrs(arr)
    >>> aga.get_ndim()
    1
    >>> aga.get_shape()
    (4,)
    >>> aga.get_size()
    4
    >>> aga.get_dtype()
    dtype('int64')
    >>> arr = np.array([[5, 5],
                        [6, 6]])
    >>> aga = ArrayGetAttrs(arr)
    >>> aga.get_ndim()
    2
    >>> aga.get_shape()
    (2, 2)
    >>> aga.get_size()
    4
    >>> aga.get_dtype()
    dtype('int64')
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 08. Define a function named `add_intercepts` which horizontally combines a `(m, 1)` array of ones to a given array.

In [ ]:
def add_intercepts(arr: np.ndarray) -> np.ndarray:
    """
    >>> A = np.array([5, 5, 6, 6]).reshape(-1, 1)
    >>> add_intercepts(A)
    array([[1, 5],
           [1, 5],
           [1, 6],
           [1, 6]])
    >>> B = np.arange(10, dtype=int).reshape(5, 2)
    >>> add_intercepts(B)
    array([[1, 0, 1],
           [1, 2, 3],
           [1, 4, 5],
           [1, 6, 7],
           [1, 8, 9]])
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 09. Define a function named `create_square_matrix` which generates a square matrix with elements equal to the multiplication of row numbers and column numbers.

In [ ]:
def create_square_matrix(n: int) -> np.ndarray:
    """
    >>> create_square_matrix(3)
    array([[1, 2, 3],
           [2, 4, 6],
           [3, 6, 9]])
    >>> create_square_matrix(4)
    array([[ 1,  2,  3,  4],
           [ 2,  4,  6,  8],
           [ 3,  6,  9, 12],
           [ 4,  8, 12, 16]])
    >>> create_square_matrix(5)
    array([[ 1,  2,  3,  4,  5],
           [ 2,  4,  6,  8, 10],
           [ 3,  6,  9, 12, 15],
           [ 4,  8, 12, 16, 20],
           [ 5, 10, 15, 20, 25]])
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## 10. Define a function named `create_diagonal_split_matrix` which generates a diagonal matrix given `n` as the order, `fill_int` as the elements outside the main diagonal and zeros as the main diagonal.

In [ ]:
def create_diagonal_split_matrix(n: int, fill_int: int) -> np.ndarray:
    """
    >>> create_diagonal_split_matrix(2, 5566)
    array([[   0, 5566],
           [5566,    0]])
    >>> create_diagonal_split_matrix(3, 55)
    array([[ 0, 55, 55],
           [55,  0, 55],
           [55, 55,  0]])
    >>> create_diagonal_split_matrix(4, 66)
    array([[ 0, 66, 66, 66],
           [66,  0, 66, 66],
           [66, 66,  0, 66],
           [66, 66, 66,  0]])
    """
    ### BEGIN SOLUTION
    
    ### END SOLUTION

## Running tests

Assignment session is finished, click Runtime -> Restart and run all to run the following tests.

In [ ]:
class TestAssignmentFour(unittest.TestCase):
    def test_01_Hogwarts(self):
        hogwarts = Hogwarts()
        self.assertIsInstance(hogwarts, Hogwarts)
        self.assertIsInstance(hogwarts.location, str)
        self.assertIsInstance(hogwarts.founders, list)
        self.assertTrue(len(hogwarts.founders) == 4)
        self.assertIsInstance(hogwarts.houses, list)
        self.assertTrue(len(hogwarts.houses) == 4)
    def test_02_Gryffindor(self):
        harry_potter = Gryffindor("Harry Potter")
        self.assertIsInstance(harry_potter, Gryffindor)
        self.assertIsInstance(harry_potter.name, str)
        self.assertIsInstance(harry_potter.traits, list)
        self.assertIsInstance(harry_potter.colors, list)
        self.assertEqual(harry_potter.cast_a_spell(), 'Expelliarmus!')
        hermione_granger = Gryffindor("Hermione Granger")
        self.assertIsInstance(hermione_granger, Gryffindor)
        self.assertIsInstance(hermione_granger.name, str)
        self.assertIsInstance(hermione_granger.traits, list)
        self.assertIsInstance(hermione_granger.colors, list)
        self.assertEqual(hermione_granger.cast_a_spell(), 'Expelliarmus!')
    def test_03_Palindrome(self):
        palindrome = Palindrome('eye')
        self.assertIsInstance(palindrome, Palindrome)
        self.assertEqual(palindrome.original_text, 'eye')
        self.assertEqual(palindrome.reversed_text, 'eye')
        self.assertTrue(palindrome.is_palindrome())
        palindrome = Palindrome('dye')
        self.assertIsInstance(palindrome, Palindrome)
        self.assertEqual(palindrome.original_text, 'dye')
        self.assertEqual(palindrome.reversed_text, 'eyd')
        self.assertFalse(palindrome.is_palindrome())
        palindrome = Palindrome('did')
        self.assertIsInstance(palindrome, Palindrome)
        self.assertEqual(palindrome.original_text, 'did')
        self.assertEqual(palindrome.reversed_text, 'did')
        self.assertTrue(palindrome.is_palindrome())
    def test_04_MinMaxFinder(self):
        min_max_finder = MinMaxFinder([2, 3, 5, 7, 11, 11, 7, 5, 3, 2])
        self.assertIsInstance(min_max_finder, MinMaxFinder)
        self.assertIsInstance(min_max_finder.integer_list, list)
        self.assertEqual(min_max_finder.find_min(), 2)
        self.assertEqual(min_max_finder.find_max(), 11)
        self.assertEqual(min_max_finder.find_idxmin(), [0, 9])
        self.assertEqual(min_max_finder.find_idxmax(), [4, 5])
        min_max_finder = MinMaxFinder([10, 9, 8, 6, 4, 1, 1, 4, 6, 8, 9, 10])
        self.assertIsInstance(min_max_finder, MinMaxFinder)
        self.assertIsInstance(min_max_finder.integer_list, list)
        self.assertEqual(min_max_finder.find_min(), 1)
        self.assertEqual(min_max_finder.find_max(), 10)
        self.assertEqual(min_max_finder.find_idxmin(), [5, 6])
        self.assertEqual(min_max_finder.find_idxmax(), [0, 11])
    def test_05_CommonDivisors(self):
        cd = CommonDivisors(3, 6)
        self.assertIsInstance(cd, CommonDivisors)
        self.assertEqual(len(cd.x_divisors), 2)
        self.assertEqual(len(cd.y_divisors), 4)
        self.assertEqual(len(cd.get_common_divisors()), 2)
        cd = CommonDivisors(4, 8)
        self.assertIsInstance(cd, CommonDivisors)
        self.assertEqual(len(cd.x_divisors), 3)
        self.assertEqual(len(cd.y_divisors), 4)
        self.assertEqual(len(cd.get_common_divisors()), 3)
    def test_06_PrimeJudger(self):
        pj = PrimeJudger(1)
        self.assertIsInstance(pj, PrimeJudger)
        self.assertEqual(len(pj.get_divisors()), 1)
        self.assertFalse(pj.is_prime())
        pj = PrimeJudger(2)
        self.assertIsInstance(pj, PrimeJudger)
        self.assertEqual(len(pj.get_divisors()), 2)
        self.assertTrue(pj.is_prime())
        pj = PrimeJudger(4)
        self.assertIsInstance(pj, PrimeJudger)
        self.assertEqual(len(pj.get_divisors()), 3)
        self.assertFalse(pj.is_prime())
    def test_07_ArrayGetAttrs(self):
        arr = np.array([5, 5, 6, 6])
        aga = ArrayGetAttrs(arr)
        self.assertIsInstance(aga, ArrayGetAttrs)
        self.assertEqual(aga.get_ndim(), 1)
        self.assertEqual(aga.get_shape(), (4,))
        self.assertEqual(aga.get_size(), 4)
        arr = np.array([[5, 5],
                        [6, 6]])
        aga = ArrayGetAttrs(arr)
        self.assertIsInstance(aga, ArrayGetAttrs)
        self.assertEqual(aga.get_ndim(), 2)
        self.assertEqual(aga.get_shape(), (2, 2))
        self.assertEqual(aga.get_size(), 4)
    def test_08_add_intercepts(self):
        A = np.array([5, 5, 6, 6]).reshape(-1, 1)
        np.testing.assert_array_equal(add_intercepts(A),
        np.array([[1, 5],
                  [1, 5],
                  [1, 6],
                  [1, 6]]))
        B = np.arange(10).reshape(5, 2)
        np.testing.assert_array_equal(add_intercepts(B),
        np.array([[1, 0, 1],
                  [1, 2, 3],
                  [1, 4, 5],
                  [1, 6, 7],
                  [1, 8, 9]]))
        C = np.array([5, 6, 7, 8]).reshape(-1, 1)
        np.testing.assert_array_equal(add_intercepts(C),
        np.array([[1, 5],
                  [1, 6],
                  [1, 7],
                  [1, 8]]))
    def test_10_create_diagonal_split_matrix(self):
        np.testing.assert_array_equal(create_diagonal_split_matrix(2, 5566),
        np.array([[   0, 5566],
                  [5566,    0]]))
        np.testing.assert_array_equal(create_diagonal_split_matrix(3, 55),
        np.array([[ 0, 55, 55],
                  [55,  0, 55],
                  [55, 55,  0]]))
        np.testing.assert_array_equal(create_diagonal_split_matrix(4, 66),
        np.array([[ 0, 66, 66, 66],
                  [66,  0, 66, 66],
                  [66, 66,  0, 66],
                  [66, 66, 66,  0]]))
    def test_09_create_square_matrix(self):
        np.testing.assert_array_equal(create_square_matrix(3),
        np.array([[1, 2, 3],
                  [2, 4, 6],
                  [3, 6, 9]]))
        np.testing.assert_array_equal(create_square_matrix(4),
        np.array([[ 1,  2,  3,  4],
                  [ 2,  4,  6,  8],
                  [ 3,  6,  9, 12],
                  [ 4,  8, 12, 16]]))
        np.testing.assert_array_equal(create_square_matrix(5),
        np.array([[ 1,  2,  3,  4,  5],
                  [ 2,  4,  6,  8, 10],
                  [ 3,  6,  9, 12, 15],
                  [ 4,  8, 12, 16, 20],
                  [ 5, 10, 15, 20, 25]]))

suite = unittest.TestLoader().loadTestsFromTestCase(TestAssignmentFour)
runner = unittest.TextTestRunner(verbosity=2)
test_results = runner.run(suite)
number_of_failures = len(test_results.failures)
number_of_errors = len(test_results.errors)
number_of_test_runs = test_results.testsRun
number_of_successes = number_of_test_runs - (number_of_failures + number_of_errors)

In [ ]:
print("You've got {} successes among {} questions.".format(number_of_successes, number_of_test_runs))